/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * CRM Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * Case_RestController as REST API
 *
 * <p>Exposes REST endpoints for the Case_ entity.</p>
 *
 * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>CRM Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core CRM capabilities across accounts, contacts, leads, opportunities, pricing, quotes, orders, service cases, activities, and campaigns.</td></tr>
 *          <tr><td>industry</td><td>CRM</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	Case_BusinessService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateCase_Command</li>
 *      <li></li>UpdateCase_Command</li>
 *      <liDeleteCase_Command</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Case_")
public class Case_RestController extends BaseSpringRestController {

    /**
     * Handles create a Case_.  if not key provided, calls create, otherwise calls save
     * @param		Case_	case_
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateCase_Command command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {       
        	
			completableFuture = Case_Service.getCase_Instance().createCase_( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a Case_.  if no key provided, calls create, otherwise calls save
     * @param		Case_ case_
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateCase_Command command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateCase_Command
			// -----------------------------------------------
			completableFuture = Case_Service.getCase_Instance().updateCase_(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "Case_Controller:update() - successfully update Case_ - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a Case_ entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestBody(required=true) DeleteCase_Command command ) {                
    	CompletableFuture<Void> completableFuture = null;
    	try {
        	Case_Service delegate = Case_Service.getCase_Instance();

        	completableFuture = delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted Case_ with key " + command.getCase_Id() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	
    /**
     * Handles loading a Case_ using a UUID
     * @param		UUID uuid 
     * @return		Case_
     */    
    @GetMapping("/load")
    public Case_ load( @RequestParam(required=true) UUID uuid ) {    	
    	Case_ entity = null;

    	try {  
    		entity = Case_Service.getCase_Instance().getCase_( new Case_FetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load Case_ using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all Case_ business objects
     * @return		Set<Case_>
     */
    @GetMapping("/")
    public List<Case_> loadAll() {                
    	List<Case_> case_List = null;
        
    	try {
            // load the Case_
            case_List = Case_Service.getCase_Instance().getAllCase_();
            
            if ( case_List != null )
                LOGGER.log( Level.INFO,  "successfully loaded all Case_s" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all Case_s ", exc );
        	return null;
        }

        return case_List;
                            
    }

    /**
     * save Organization on Case_
     * @param		command AssignOrganizationToCase_Command
     */     
	@PutMapping("/assignOrganization")
	public void assignOrganization( @RequestBody AssignOrganizationToCase_Command command ) {
		try {
			Case_Service.getCase_Instance().assignOrganization( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Organization", exc );
        }
	}

    /**
     * unassign Organization on Case_
     * @param		 command UnAssignOrganizationFromCase_Command
     */     
	@PutMapping("/unAssignOrganization")
	public void unAssignOrganization( @RequestBody(required=true)  UnAssignOrganizationFromCase_Command command ) {
		try {
			Case_Service.getCase_Instance().unAssignOrganization( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Organization", exc );
		}
	}
	
    /**
     * save Account on Case_
     * @param		command AssignAccountToCase_Command
     */     
	@PutMapping("/assignAccount")
	public void assignAccount( @RequestBody AssignAccountToCase_Command command ) {
		try {
			Case_Service.getCase_Instance().assignAccount( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Account", exc );
        }
	}

    /**
     * unassign Account on Case_
     * @param		 command UnAssignAccountFromCase_Command
     */     
	@PutMapping("/unAssignAccount")
	public void unAssignAccount( @RequestBody(required=true)  UnAssignAccountFromCase_Command command ) {
		try {
			Case_Service.getCase_Instance().unAssignAccount( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Account", exc );
		}
	}
	
    /**
     * save Contact on Case_
     * @param		command AssignContactToCase_Command
     */     
	@PutMapping("/assignContact")
	public void assignContact( @RequestBody AssignContactToCase_Command command ) {
		try {
			Case_Service.getCase_Instance().assignContact( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Contact", exc );
        }
	}

    /**
     * unassign Contact on Case_
     * @param		 command UnAssignContactFromCase_Command
     */     
	@PutMapping("/unAssignContact")
	public void unAssignContact( @RequestBody(required=true)  UnAssignContactFromCase_Command command ) {
		try {
			Case_Service.getCase_Instance().unAssignContact( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Contact", exc );
		}
	}
	
    /**
     * save Owner on Case_
     * @param		command AssignOwnerToCase_Command
     */     
	@PutMapping("/assignOwner")
	public void assignOwner( @RequestBody AssignOwnerToCase_Command command ) {
		try {
			Case_Service.getCase_Instance().assignOwner( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Owner", exc );
        }
	}

    /**
     * unassign Owner on Case_
     * @param		 command UnAssignOwnerFromCase_Command
     */     
	@PutMapping("/unAssignOwner")
	public void unAssignOwner( @RequestBody(required=true)  UnAssignOwnerFromCase_Command command ) {
		try {
			Case_Service.getCase_Instance().unAssignOwner( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Owner", exc );
		}
	}
	
    /**
     * save Team on Case_
     * @param		command AssignTeamToCase_Command
     */     
	@PutMapping("/assignTeam")
	public void assignTeam( @RequestBody AssignTeamToCase_Command command ) {
		try {
			Case_Service.getCase_Instance().assignTeam( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Team", exc );
        }
	}

    /**
     * unassign Team on Case_
     * @param		 command UnAssignTeamFromCase_Command
     */     
	@PutMapping("/unAssignTeam")
	public void unAssignTeam( @RequestBody(required=true)  UnAssignTeamFromCase_Command command ) {
		try {
			Case_Service.getCase_Instance().unAssignTeam( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Team", exc );
		}
	}
	

    /**
     * save Activities on Case_
     * @param		command AssignActivitiesToCase_Command
     */     
	@PutMapping("/addToActivities")
	public void addToActivities( @RequestBody(required=true) AssignActivitiesToCase_Command command ) {
		try {
			Case_Service.getCase_Instance().addToActivities( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Activities", exc );
		}
	}

    /**
     * remove Activities on Case_
     * @param		command RemoveActivitiesFromCase_Command
     */     	
	@PutMapping("/removeFromActivities")
	public void removeFromActivities( 	@RequestBody(required=true) RemoveActivitiesFromCase_Command command )
	{		
		try {
			Case_Service.getCase_Instance().removeFromActivities( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Activities", exc );
		}
	}

    /**
     * save CaseComments on Case_
     * @param		command AssignCaseCommentsToCase_Command
     */     
	@PutMapping("/addToCaseComments")
	public void addToCaseComments( @RequestBody(required=true) AssignCaseCommentsToCase_Command command ) {
		try {
			Case_Service.getCase_Instance().addToCaseComments( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set CaseComments", exc );
		}
	}

    /**
     * remove CaseComments on Case_
     * @param		command RemoveCaseCommentsFromCase_Command
     */     	
	@PutMapping("/removeFromCaseComments")
	public void removeFromCaseComments( 	@RequestBody(required=true) RemoveCaseCommentsFromCase_Command command )
	{		
		try {
			Case_Service.getCase_Instance().removeFromCaseComments( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set CaseComments", exc );
		}
	}

    /**
     * save Emails on Case_
     * @param		command AssignEmailsToCase_Command
     */     
	@PutMapping("/addToEmails")
	public void addToEmails( @RequestBody(required=true) AssignEmailsToCase_Command command ) {
		try {
			Case_Service.getCase_Instance().addToEmails( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Emails", exc );
		}
	}

    /**
     * remove Emails on Case_
     * @param		command RemoveEmailsFromCase_Command
     */     	
	@PutMapping("/removeFromEmails")
	public void removeFromEmails( 	@RequestBody(required=true) RemoveEmailsFromCase_Command command )
	{		
		try {
			Case_Service.getCase_Instance().removeFromEmails( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Emails", exc );
		}
	}

    /**
     * save RelatedOpportunities on Case_
     * @param		command AssignRelatedOpportunitiesToCase_Command
     */     
	@PutMapping("/addToRelatedOpportunities")
	public void addToRelatedOpportunities( @RequestBody(required=true) AssignRelatedOpportunitiesToCase_Command command ) {
		try {
			Case_Service.getCase_Instance().addToRelatedOpportunities( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set RelatedOpportunities", exc );
		}
	}

    /**
     * remove RelatedOpportunities on Case_
     * @param		command RemoveRelatedOpportunitiesFromCase_Command
     */     	
	@PutMapping("/removeFromRelatedOpportunities")
	public void removeFromRelatedOpportunities( 	@RequestBody(required=true) RemoveRelatedOpportunitiesFromCase_Command command )
	{		
		try {
			Case_Service.getCase_Instance().removeFromRelatedOpportunities( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set RelatedOpportunities", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Case_ case_ = null;
    private static final Logger LOGGER = Logger.getLogger(Case_RestController.class.getName());
    
}
