/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * CRM Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * ProductRestController as REST API
 *
 * <p>Exposes REST endpoints for the Product entity.</p>
 *
 * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>CRM Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core CRM capabilities across accounts, contacts, leads, opportunities, pricing, quotes, orders, service cases, activities, and campaigns.</td></tr>
 *          <tr><td>industry</td><td>CRM</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	ProductBusinessService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateProductCommand</li>
 *      <li></li>UpdateProductCommand</li>
 *      <liDeleteProductCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Product")
public class ProductRestController extends BaseSpringRestController {

    /**
     * Handles create a Product.  if not key provided, calls create, otherwise calls save
     * @param		Product	product
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateProductCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {       
        	
			completableFuture = ProductService.getProductInstance().createProduct( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a Product.  if no key provided, calls create, otherwise calls save
     * @param		Product product
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateProductCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateProductCommand
			// -----------------------------------------------
			completableFuture = ProductService.getProductInstance().updateProduct(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "ProductController:update() - successfully update Product - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a Product entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestBody(required=true) DeleteProductCommand command ) {                
    	CompletableFuture<Void> completableFuture = null;
    	try {
        	ProductService delegate = ProductService.getProductInstance();

        	completableFuture = delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted Product with key " + command.getProductId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	
    /**
     * Handles loading a Product using a UUID
     * @param		UUID uuid 
     * @return		Product
     */    
    @GetMapping("/load")
    public Product load( @RequestParam(required=true) UUID uuid ) {    	
    	Product entity = null;

    	try {  
    		entity = ProductService.getProductInstance().getProduct( new ProductFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load Product using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all Product business objects
     * @return		Set<Product>
     */
    @GetMapping("/")
    public List<Product> loadAll() {                
    	List<Product> productList = null;
        
    	try {
            // load the Product
            productList = ProductService.getProductInstance().getAllProduct();
            
            if ( productList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all Products" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all Products ", exc );
        	return null;
        }

        return productList;
                            
    }

    /**
     * save Organization on Product
     * @param		command AssignOrganizationToProductCommand
     */     
	@PutMapping("/assignOrganization")
	public void assignOrganization( @RequestBody AssignOrganizationToProductCommand command ) {
		try {
			ProductService.getProductInstance().assignOrganization( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Organization", exc );
        }
	}

    /**
     * unassign Organization on Product
     * @param		 command UnAssignOrganizationFromProductCommand
     */     
	@PutMapping("/unAssignOrganization")
	public void unAssignOrganization( @RequestBody(required=true)  UnAssignOrganizationFromProductCommand command ) {
		try {
			ProductService.getProductInstance().unAssignOrganization( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Organization", exc );
		}
	}
	

    /**
     * save PriceBookEntries on Product
     * @param		command AssignPriceBookEntriesToProductCommand
     */     
	@PutMapping("/addToPriceBookEntries")
	public void addToPriceBookEntries( @RequestBody(required=true) AssignPriceBookEntriesToProductCommand command ) {
		try {
			ProductService.getProductInstance().addToPriceBookEntries( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set PriceBookEntries", exc );
		}
	}

    /**
     * remove PriceBookEntries on Product
     * @param		command RemovePriceBookEntriesFromProductCommand
     */     	
	@PutMapping("/removeFromPriceBookEntries")
	public void removeFromPriceBookEntries( 	@RequestBody(required=true) RemovePriceBookEntriesFromProductCommand command )
	{		
		try {
			ProductService.getProductInstance().removeFromPriceBookEntries( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set PriceBookEntries", exc );
		}
	}

    /**
     * save OpportunityLineItems on Product
     * @param		command AssignOpportunityLineItemsToProductCommand
     */     
	@PutMapping("/addToOpportunityLineItems")
	public void addToOpportunityLineItems( @RequestBody(required=true) AssignOpportunityLineItemsToProductCommand command ) {
		try {
			ProductService.getProductInstance().addToOpportunityLineItems( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set OpportunityLineItems", exc );
		}
	}

    /**
     * remove OpportunityLineItems on Product
     * @param		command RemoveOpportunityLineItemsFromProductCommand
     */     	
	@PutMapping("/removeFromOpportunityLineItems")
	public void removeFromOpportunityLineItems( 	@RequestBody(required=true) RemoveOpportunityLineItemsFromProductCommand command )
	{		
		try {
			ProductService.getProductInstance().removeFromOpportunityLineItems( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set OpportunityLineItems", exc );
		}
	}

    /**
     * save QuoteLineItems on Product
     * @param		command AssignQuoteLineItemsToProductCommand
     */     
	@PutMapping("/addToQuoteLineItems")
	public void addToQuoteLineItems( @RequestBody(required=true) AssignQuoteLineItemsToProductCommand command ) {
		try {
			ProductService.getProductInstance().addToQuoteLineItems( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set QuoteLineItems", exc );
		}
	}

    /**
     * remove QuoteLineItems on Product
     * @param		command RemoveQuoteLineItemsFromProductCommand
     */     	
	@PutMapping("/removeFromQuoteLineItems")
	public void removeFromQuoteLineItems( 	@RequestBody(required=true) RemoveQuoteLineItemsFromProductCommand command )
	{		
		try {
			ProductService.getProductInstance().removeFromQuoteLineItems( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set QuoteLineItems", exc );
		}
	}

    /**
     * save OrderItems on Product
     * @param		command AssignOrderItemsToProductCommand
     */     
	@PutMapping("/addToOrderItems")
	public void addToOrderItems( @RequestBody(required=true) AssignOrderItemsToProductCommand command ) {
		try {
			ProductService.getProductInstance().addToOrderItems( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set OrderItems", exc );
		}
	}

    /**
     * remove OrderItems on Product
     * @param		command RemoveOrderItemsFromProductCommand
     */     	
	@PutMapping("/removeFromOrderItems")
	public void removeFromOrderItems( 	@RequestBody(required=true) RemoveOrderItemsFromProductCommand command )
	{		
		try {
			ProductService.getProductInstance().removeFromOrderItems( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set OrderItems", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Product product = null;
    private static final Logger LOGGER = Logger.getLogger(ProductRestController.class.getName());
    
}
